vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        admin_avatar:
            uri_prefix: /media/avatar
            upload_destination: avatar_image_fs
            namer: Vich\UploaderBundle\Naming\OrignameNamer
