Sylius\Component\Customer\Model\Customer:
    attributes:
        id:
            expose: true
            type: integer
            groups: [customer:read:default, customer:read:detailed]
        email:
            expose: true
            type: string
            groups: [customer:read:default, customer:read:detailed, customer:write]
        emailCanonical:
            expose: true
            type: string
            groups: [customer:read:detailed]
        firstName:
            expose: true
            type: string
            groups: [customer:read:default, customer:read:detailed, customer:write]
        lastName:
            expose: true
            type: string
            groups: [customer:read:default, customer:read:detailed, customer:write]
        gender:
            expose: true
            type: string
            groups: [customer:read:detailed, customer:write]
        birthday:
            expose: true
            type: DateTime
            groups: [customer:read:detailed, customer:write]
        group:
            expose: true
            groups: [customer:read:detailed]
        phoneNumber:
            expose: true
            groups: [customer:write]
        subscribedToNewsletter:
            expose: true
            groups: [customer:write]
