Sylius\Component\User\Model\User:
    attributes:
        id:
            expose: true
            type: integer
            groups: [user:read:default, user:read:detailed]
        username:
            expose: true
            type: string
            groups: [user:read:default, user:read:detailed, user:write]
        usernameCanonical:
            expose: true
            type: string
            groups: [user:read:detailed]
        email:
            expose: false
            type: string
        emailCanonical:
            expose: false
            type: string
        enabled:
            expose: true
            type: boolean
            groups: [user:read:default, user:read:detailed]
        plainPassword:
            groups: [user:write]
        roles:
            expose: true
            type: array
            groups: [user:read:detailed]
