imports:
    - { resource: '../vendor/monofony/monofony/tests/Behat/Resources/config/services.yaml' }
    - { resource: services_test/contexts.yaml }
    - { resource: services_test/elements.yaml }
    - { resource: services_test/pages.yaml }
